sudu: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t iamjdg11/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true iamjdg11/docker-react-app npm run test -- --coverage

deoply:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: ""
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  sercret_access_key: $AWS_SECRET_ACCESS_KEY
